# Target platform: Ubuntu 18.04 with Nvidia JetPack 32.7.1 (PyTorch 1.10)
# This file generate the docker.io/flbench/18.04-jnano:1.0.0 image.
# It is based on the flbench-paper branch and not up to date with the master branch.
# Reason: Nvidia has discontinued the Jetson Nano 2GB (2020) product line.

FROM nvcr.io/nvidia/l4t-pytorch:r32.7.1-pth1.10-py3

# RUN rm /usr/share/keyrings/kitware-archive-keyring.gpg
# RUN apt-get install kitware-archive-keyring
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ bionic main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null

# Basics installation
RUN apt-get update
RUN apt-get install software-properties-common git wget curl pkg-config -y

# Package installation
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN apt-get install git wget curl pkg-config ansible python3-virtualenv virtualenv tmux unzip libjpeg-dev libopenblas-dev libopenmpi-dev libomp-dev libsndfile1-dev build-essential libhdf5-dev python3-apt build-essential libhdf5-dev -y
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN add-apt-repository 'deb http://apt.llvm.org/bionic/   llvm-toolchain-bionic-10  main'
RUN apt update
RUN apt-get install llvm-10 lldb-10 llvm-10-dev libllvm10 llvm-10-runtime -y
RUN LLVM_CONFIG=/usr/bin/llvm-config-10 pip3 install llvmlite

# Install python project dependencies
RUN pip3 install --upgrade pip wheel setuptools
COPY requirements/requirements_ubuntu_1804_py36.txt requirements.txt
RUN LLVM_CONFIG=/usr/bin/llvm-config-10 pip3 install -r requirements.txt --ignore-installed

# Optional: Copy netrc config for W&B monitoring
# COPY ~/.netrc .netrc

# Copy project files
WORKDIR /opt/flbench
RUN git clone -b submission --recurse-submodules https://github.com/laminair/FLEdge.git /opt/flbench
