#!/usr/bin/env bash

cd $( dirname -- "$( readlink -f -- "$0"; )"; ) # Here we make sure to set the right pwd
cd terraform

if [ ! -d ".terraform" ]; then
  terraform init
fi

terraform apply -var-file="credentials.tfvars"
cd ..
echo "Waiting 45 seconds for all VMs to come alive..."
sleep 45 # Here we wait 45 seconds for all VMs to come alive

# The inventory file will be generated by the Terraform output.
ansible-playbook -c ssh ansible/automate-deployment.yaml -i ansible/inventory_static.cfg
